name: feedback
description: A Flutter package for getting better feedback. It allows the user to give interactive feedback directly in the app.
version: 0.2.1+1
author: Jonas UekÃ¶tter
homepage: https://uekoetter.dev
repository: https://github.com/ueman/feedback
issue_tracker: https://github.com/ueman/feedback/issues

environment:
  sdk: '>=2.2.2 <3.0.0'
  flutter: '>=1.12.13 <2.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: