name: example
description: A new Flutter project.

publish_to: none

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  cupertino_icons: ^1.0.3
  feedback:
    path: ../../feedback
  flutter:
    sdk: flutter
  flutter_email_sender: ^5.1.0
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.2
  http: ^0.13.0
  path_provider: ^2.0.10
  share_plus: ^6.0.0
  url_launcher: ^6.1.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
