name: feedback_sentry
description: A Flutter package for getting better feedback. It allows the user to give interactive feedback directly in the app and upload it to Sentry.io
version: 2.3.0
homepage: https://uekoetter.dev
repository: https://github.com/ueman/feedback
issue_tracker: https://github.com/ueman/feedback/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter
  feedback: ^2.2.0
  sentry: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true