name: feedback_sentry
description: A simple way to to send user feedback with images to Sentry.io
version: 2.0.0
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter
  feedback: ^2.0.0
  sentry: ^6.0.0-0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true