name: feedback_sentry

on:
  push:
    branches:
      - master
    paths:
      - "feedback_sentry/**"
      - ".github/workflows/sentry.yml"
  pull_request:
    paths:
      - "feedback_sentry/**"
      - ".github/workflows/sentry.yml"

jobs:
  check:
    defaults:
      run:
        working-directory: feedback_sentry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '12.x'
          distribution: 'adopt'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter format -n --set-exit-if-changed .
      - run: flutter analyze
      - run: flutter test --coverage
      - uses: codecov/codecov-action@v1.5.2